import pandas as pd
from typing import Protocol, List
from datetime import datetime
from .models import Order, Position, AccountBalance, MarketData, OrderStatus, Candlestick, TimeFrame

class BrokerAdapter(Protocol):
    def connect(self) -> bool:
        ...
    def disconnect(self) -> bool:
        ...
    def get_account_balance(self) -> AccountBalance:
        ...
    def get_positions(self) -> List[Position]:
        ...
    def place_order(self, order: Order) -> tuple[str, str]:
        ...
    def cancel_order(self, order_id: str) -> bool:
        ...
    def get_order_status(self, order_id: str) -> OrderStatus:
        ...

class MarketDataProvider(Protocol):
    def connect(self) -> bool:
        ...
    def disconnect(self) -> bool:
        ...
    def get_latest_quote(self, symbol: str) -> MarketData:
        ...
    def get_historical_candlesticks(self, symbol: str | list[str], start: datetime, end: datetime, timeframe: TimeFrame) -> pd.DataFrame:
        ...
